### ISSUE TITLE
qcbc ambiguous out only saves the last overlapping subsequence

### ISSUE THREAD

**Issue by lauraluebbert** [pachterlab/qcbc#1]
When the `-o` flag is used to save the output from qcbc ambiguous, it only saves the last result.

Example:
```
qcbc ambiguous -l 2 -o "test_out.txt" "test.txt"
```
with test.txt:
GTCGA	tag1
TCGGA	tag2
TCTGA	tag3

This returns the following in test_out.txt:
GA	tag1,tag2,tag3

But it should be:
TC	tag1,tag2,tag3
CG	tag1,tag2
GA	tag1,tag2,tag3

**Comment by sbooeshaghi** [comment]
Resolved with https://github.com/pachterlab/qcbc/commit/ff4acbb727ba9e1ea3e1b3c1d84167ccf5f09f4f (thank you for the PR!)
